name: Runner Sanity Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker info (debug)
        run: docker info
      
      - name: List files (debug)

        run: ls -lha

      - name: Build Docker image
        run: |
           docker build --no-cache -t devops-lab:teste .

      -  name: Run container
         run: |
           docker run --rm devops-lab:teste
           
